export const tagTypes = [
  "Management",
  "Reference",
  "Attendance",
  "Dashboard",
  "Leave",
  "Devices",
  "Reports",
  "DriveCosts",
  "Profile",
  "Audit",
  "DailyExpensesSummary",
  "DailyExpensesTransactions",
  "DailyExpensesCategories",
] as const;
